version: '3.8'

volumes:
  tilesrc:
  tileout:
  odtileslog:
  apachelog:

services:
  base:
    build:
      context: base/
      dockerfile: Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}
        - UWSGI_WORKERS=${UWSGI_WORKERS}
        - UWSGI_PORT=${UWSGI_PORT}
        - TILE_SOURCE_FOLDER=${TILE_SOURCE_FOLDER}
        - TILE_OUTPUT_FOLDER=${TILE_OUTPUT_FOLDER}
        - TILE_MAX_AGE=${TILE_MAX_AGE}
        - TILE_MAX_AGE_LIVE=${TILE_MAX_AGE_LIVE}
    volumes:
      - tilesrc:${TILE_SOURCE_FOLDER}
      - tileout:${TILE_OUTPUT_FOLDER}
      - odtileslog:/opt/odtiles/logs/
    restart: always

  httpd:
    build:
      context: httpd/
      dockerfile: Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}
        - SERVER_ADMIN=${SERVER_ADMIN}
    volumes:
      - apachelog:/usr/local/apache2/logs/
    ports:
      - "443:443"
    restart: always
