version: '3'

volumes:
  odtileslog:
  apachelog:

services:
  base:
    build:
      context: base/
      dockerfile: Dockerfile
      args:
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - UWSGI_WORKERS=${UWSGI_WORKERS}
        - UWSGI_PORT=${UWSGI_PORT}
        - TILE_MAX_AGE=${TILE_MAX_AGE}
        - TILE_MAX_AGE_LIVE=${TILE_MAX_AGE_LIVE}
    volumes:
      - ${TILE_SOURCE_FOLDER}:/mnt/odtiles/tilesrc
      - ${TILE_OUTPUT_FOLDER}:/mnt/odtiles/tileout
      - odtileslog:/opt/odtiles/logs/
      - apachelog:/usr/local/apache2/logs/
    restart: always

  httpd:
    build:
      context: httpd/
      dockerfile: Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}
        - SERVER_ADMIN=${SERVER_ADMIN}
    volumes:
      - apachelog:/usr/local/apache2/logs/
    ports:
      - "80:80"
      - "443:443"
    restart: always
